language: go
sudo: false  # silence warning

addons:
  apt:
    packages:
    - libxml2-dev
    - libxmlsec1-dev

go:
  - 1.6
  - 1.7

install:
 - go get -t ./...
 - go get github.com/golang/lint/golint

script:
 - golint *.go
 - go vet ./...
 - go test -v ./...
